name: cartoongan
channels:
  - defaults
dependencies:
  - asn1crypto
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - conda
  
  - freetype
  - idna
  - imageio
  - intel-openmp
  - jpeg


  
  
  - libpng

  - libtiff
  - mkl
  - mkl_fft
  - mkl_random

  - numpy
  - numpy-base
  - olefile
  - openssl
  - pillow
  - pip
  - pycosat
  - pycparser
  - pyopenssl
  - pysocks
  - python
  
  - requests
  - ruamel_yaml
  - setuptools
  - six
  - sqlite
  - tk
  - tqdm
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.21.1
    - h5py==2.8.0
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - protobuf==3.8.0
    - pyyaml==5.1.1
    - scipy==1.3.0
    - tb-nightly==1.14.0a20190301
    - tensorflow==2.0.0a0
    - tensorflow-estimator-2-0-preview==1.14.0.dev2019060900
    - tensorflow-hub==0.3.0
    - tensorflowjs==1.1.2
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019030115
    - tf-nightly-2-0-preview==2.0.0.dev20190608
    - werkzeug==0.15.4
    - wrapt==1.11.1
    - libstdcxx-ng
    - libffi
    - libedit
    - libgcc-ng
    - libgfortran-ng
    - readline
    - ncurses
    - cryptograph